name: gitleaks
on:
  pull_request:
jobs:
  hello:
    runs-on: self-hosted
    name: Secure Code Scanning
    steps:
      - run: python3 /home/ubuntu/actions-runner/scan.py -p ${{ github.event.pull_request.html_url }} -n ${{github.repository_id}}_${{ github.event.pull_request.number }}.txt -r ${{ github.repository}}
      - name: Comment request
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: /home/ubuntu/actions-runner/${{github.repository_id}}_${{ github.event.pull_request.number }}.txt
